export const PATH = {
  all: '*',
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  term: '/term',
  profile: '/profile',
  dashboard: '/dashboard',
  order: '/order',
  product: '/product',
  category: '/category',
  customer: '/customer',
  report: '/report',
  salesdeal: '/salesdeal',
  chat: '/chat',
  Knowledge: '/Knowledge',
  productUpdates: '/productUpdates',
  settingsUser: '/settingsUser',
  settingsCommunity: '/settingsCommunity',
};
