export const PATH = {
  all: '*',
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  term: '/term',
  profile: '/profile',
  dashboard: '/dashboard',
  revenueDashboard: '/dashboard/revenue',
  order: '/order',
  orderDetail: '/order/:id',
  orderDetailById: (id: any) => `/order/${id}`,
  product: '/product',
  addProduct: '/product/add',
  inventory: '/inventory',
  inventoryDetail: '/inventory/:id',
  inventoryDetailById: (id: any) => `/inventory/${id}`,
  productDetail: '/product/:id',
  productDetailById: (id: any) => `/product/${id}`,
  category: '/category',
  categoryDetail: '/category/:id',
  categoryDetailById: (id: any) => `/category/${id}`,
  customer: '/customer',
  report: '/report',
  salesdeal: '/salesdeal',
  chat: '/chat',
  Knowledge: '/Knowledge',
  productUpdates: '/productUpdates',
  settingsUser: '/settingsUser',
  settingsCommunity: '/settingsCommunity',
};
