name: Build and Deploy Sharebuy-FE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build the Docker image
      run: docker build -t khanh2608/sharebuy-fe .
    - name: Push the Docker image
      run: docker push khanh2608/sharebuy-fe

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/sharebuy-fe-depl.yaml
        kubectl rollout restart deployment sharebuy-fe-deployment